/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControllerDelivery;
import controller.ControllerItensPedidosDelivery;
import controller.ControllerProdutos;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.ModelItensPedidosDelivery;
import model.ModelProdutos;

/**
 *
 * @author blsoft
 */
public class ViewCozinha extends javax.swing.JFrame {
    
    ControllerItensPedidosDelivery controllerItensPedidosDelivery = new ControllerItensPedidosDelivery();
    ControllerDelivery controllerDelivery = new ControllerDelivery();
    ModelItensPedidosDelivery modelItensPedidosDelivery = new ModelItensPedidosDelivery();
    ArrayList<ModelItensPedidosDelivery> listaModelItensPedidosDeliverys = new ArrayList<>();
    ModelProdutos modelProdutos = new ModelProdutos();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    /**
     * Creates new form ViewCozinha
     */
    public ViewCozinha() {
        initComponents();
        carregarPedidos();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        btAlterarStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefone", "Cod.Prod.", "Produto", "Quant.", "Status", "OBservação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbProdutos);

        btAlterarStatus.setBackground(new java.awt.Color(102, 255, 153));
        btAlterarStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Modify.png"))); // NOI18N
        btAlterarStatus.setText("Alterar status");
        btAlterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(btAlterarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterarStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAlterarStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCozinha().setVisible(true);
            }
        });
    }

    private void carregarPedidos() {
        listaModelItensPedidosDeliverys = new ArrayList<>();
        listaModelItensPedidosDeliverys = controllerItensPedidosDelivery.getListaItensPedidosDeliveryController();
        DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();

            //setar dados dos produtos
            for (int i = 0; i < listaModelItensPedidosDeliverys.size(); i++) {
                //buscar nome do produto
                modelProdutos = new ModelProdutos();
                modelProdutos =  controllerProdutos.getProdutosController(listaModelItensPedidosDeliverys.get(i).getCodigoProduto());
                
                modelo.addRow(new Object[]{
                    listaModelItensPedidosDeliverys.get(i).getCodigoTelefone(),
                    listaModelItensPedidosDeliverys.get(i).getCodigoProduto(),
                    modelProdutos.getNome(),
                    listaModelItensPedidosDeliverys.get(i).getQuantidade(),
                    listaModelItensPedidosDeliverys.get(i).getStatusPeido(),
                    listaModelItensPedidosDeliverys.get(i).getObservacao()
                });
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarStatus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbProdutos;
    // End of variables declaration//GEN-END:variables
}
