/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import commons.report.pkg1.pkg8.pkg2.vreport;
import controller.ControllerCliente;
import controller.ControllerFornecedor;
import controller.ControllerPermissaousuario;
import controller.ControllerProdutos;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModelPermissaousuario;
import model.ModelSessaoUsuario;
import util.AguardeGerandoRelatorio;
import util.BLDatas;

/**
 *
 * @author Vitor Aguiar desenvolvimento de Sistemas
 *
 */
public class ViewiPrincipal extends javax.swing.JFrame {
    
    String pNomeUsuario;
  
    /**
     * Creates new form ViewPrincipal
     */
    public ViewiPrincipal() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        configurar();
        liberarModulos();
        centralizarContainer(jpPainelDeFundo, jpMenuCentral);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jpPainelDeFundo = new componentes.UJPanelImagem();
        jpMenuCentral = new javax.swing.JPanel();
        btProdutos = new javax.swing.JButton();
        btRegistrarVenda = new javax.swing.JButton();
        btVendaMesas = new javax.swing.JButton();
        btPDV = new javax.swing.JButton();
        btContaspagar = new javax.swing.JButton();
        btContasReceber = new javax.swing.JButton();
        btFluxoCaixa = new javax.swing.JButton();
        btCliente = new javax.swing.JButton();
        btDelivery = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnuSair = new javax.swing.JMenuItem();
        jmCadastrar = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiProdutos = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jmiUsuario = new javax.swing.JMenuItem();
        miCidades = new javax.swing.JMenuItem();
        miEmpresa = new javax.swing.JMenuItem();
        miUnidadeMedida = new javax.swing.JMenuItem();
        miFormaPagamento = new javax.swing.JMenuItem();
        jmVendas = new javax.swing.JMenu();
        jmiRegistrarVenda = new javax.swing.JMenuItem();
        jmiConsultarVenda = new javax.swing.JMenuItem();
        miOrcamento = new javax.swing.JMenuItem();
        miPDV = new javax.swing.JMenuItem();
        jmiDelivery = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiRelClientes = new javax.swing.JMenuItem();
        jmiRelFornecedor = new javax.swing.JMenuItem();
        jmiRelProdutos = new javax.swing.JMenuItem();
        jmiRelatorioVendasPeriodo = new javax.swing.JMenuItem();
        jmiRelatorioVenda = new javax.swing.JMenuItem();
        jmiRelatorioContasPagar = new javax.swing.JMenuItem();
        miRelatorioContasReceber = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmFinanceiro = new javax.swing.JMenu();
        jmiContasPagar = new javax.swing.JMenuItem();
        jmiContasReceber = new javax.swing.JMenuItem();
        miFluxoCaixa = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("jMenu4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLBar Pro");
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);

        jpPainelDeFundo.setImagem(new java.io.File("C:\\BLBar\\src\\imagens\\blbar5.png"));

        jpMenuCentral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu de acesso rápido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Component.png"))); // NOI18N
        btProdutos.setText("Produtos");
        btProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btProdutos.setEnabled(false);
        btProdutos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btProdutos.setMaximumSize(new java.awt.Dimension(200, 40));
        btProdutos.setMinimumSize(new java.awt.Dimension(200, 40));
        btProdutos.setPreferredSize(new java.awt.Dimension(200, 40));
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });

        btRegistrarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Shopping cart.png"))); // NOI18N
        btRegistrarVenda.setText("Registrrar venda");
        btRegistrarVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRegistrarVenda.setEnabled(false);
        btRegistrarVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRegistrarVenda.setMaximumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.setMinimumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.setPreferredSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarVendaActionPerformed(evt);
            }
        });

        btVendaMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Shopping cart.png"))); // NOI18N
        btVendaMesas.setText("Venda por mesa");
        btVendaMesas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btVendaMesas.setEnabled(false);
        btVendaMesas.setFocusable(false);
        btVendaMesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btVendaMesas.setMaximumSize(new java.awt.Dimension(200, 40));
        btVendaMesas.setMinimumSize(new java.awt.Dimension(200, 40));
        btVendaMesas.setPreferredSize(new java.awt.Dimension(200, 40));
        btVendaMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendaMesasActionPerformed(evt);
            }
        });

        btPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Shopping cart.png"))); // NOI18N
        btPDV.setText("Venda em PDV");
        btPDV.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btPDV.setEnabled(false);
        btPDV.setFocusable(false);
        btPDV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPDV.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btPDV.setMaximumSize(new java.awt.Dimension(200, 40));
        btPDV.setMinimumSize(new java.awt.Dimension(200, 40));
        btPDV.setPreferredSize(new java.awt.Dimension(200, 40));
        btPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPDVActionPerformed(evt);
            }
        });

        btContaspagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Upload.png"))); // NOI18N
        btContaspagar.setText("Contas a pagar");
        btContaspagar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btContaspagar.setEnabled(false);
        btContaspagar.setFocusable(false);
        btContaspagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btContaspagar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btContaspagar.setMaximumSize(new java.awt.Dimension(200, 40));
        btContaspagar.setMinimumSize(new java.awt.Dimension(200, 40));
        btContaspagar.setPreferredSize(new java.awt.Dimension(200, 40));
        btContaspagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaspagarActionPerformed(evt);
            }
        });

        btContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Download.png"))); // NOI18N
        btContasReceber.setText("Contas a receber");
        btContasReceber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btContasReceber.setEnabled(false);
        btContasReceber.setFocusable(false);
        btContasReceber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btContasReceber.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btContasReceber.setMaximumSize(new java.awt.Dimension(200, 40));
        btContasReceber.setMinimumSize(new java.awt.Dimension(200, 40));
        btContasReceber.setPreferredSize(new java.awt.Dimension(200, 40));
        btContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContasReceberActionPerformed(evt);
            }
        });

        btFluxoCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Left-right.png"))); // NOI18N
        btFluxoCaixa.setText("Fluxo de caixa");
        btFluxoCaixa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btFluxoCaixa.setEnabled(false);
        btFluxoCaixa.setFocusable(false);
        btFluxoCaixa.setHideActionText(true);
        btFluxoCaixa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFluxoCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btFluxoCaixa.setMaximumSize(new java.awt.Dimension(200, 40));
        btFluxoCaixa.setMinimumSize(new java.awt.Dimension(200, 40));
        btFluxoCaixa.setPreferredSize(new java.awt.Dimension(200, 40));
        btFluxoCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFluxoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFluxoCaixaActionPerformed(evt);
            }
        });

        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/People.png"))); // NOI18N
        btCliente.setText("Cliente");
        btCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btCliente.setEnabled(false);
        btCliente.setFocusable(false);
        btCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btCliente.setMaximumSize(new java.awt.Dimension(200, 40));
        btCliente.setMinimumSize(new java.awt.Dimension(200, 40));
        btCliente.setPreferredSize(new java.awt.Dimension(200, 40));
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        btDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Shopping cart.png"))); // NOI18N
        btDelivery.setText("Delivery");
        btDelivery.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btDelivery.setEnabled(false);
        btDelivery.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btDelivery.setMaximumSize(new java.awt.Dimension(200, 40));
        btDelivery.setMinimumSize(new java.awt.Dimension(200, 40));
        btDelivery.setPreferredSize(new java.awt.Dimension(200, 40));
        btDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeliveryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuCentralLayout = new javax.swing.GroupLayout(jpMenuCentral);
        jpMenuCentral.setLayout(jpMenuCentralLayout);
        jpMenuCentralLayout.setHorizontalGroup(
            jpMenuCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuCentralLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpMenuCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuCentralLayout.createSequentialGroup()
                        .addComponent(btPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btContaspagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenuCentralLayout.createSequentialGroup()
                        .addGroup(jpMenuCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpMenuCentralLayout.createSequentialGroup()
                                .addComponent(btRegistrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btContasReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpMenuCentralLayout.createSequentialGroup()
                                .addComponent(btVendaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpMenuCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btFluxoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpMenuCentralLayout.setVerticalGroup(
            jpMenuCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuCentralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jpMenuCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpMenuCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btVendaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btFluxoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpMenuCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btContasReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpMenuCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btContaspagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPainelDeFundoLayout = new javax.swing.GroupLayout(jpPainelDeFundo);
        jpPainelDeFundo.setLayout(jpPainelDeFundoLayout);
        jpPainelDeFundoLayout.setHorizontalGroup(
            jpPainelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPainelDeFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpMenuCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        jpPainelDeFundoLayout.setVerticalGroup(
            jpPainelDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelDeFundoLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jpMenuCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Logado como:");

        jlUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlUsuario.setText("usuaario");

        jlData.setForeground(new java.awt.Color(255, 255, 255));
        jlData.setText("data");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data/Hora de login:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlData))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alt+C = Clientes   -   Alt+P = Produtos   -   Alt+F = Fornecedor   -   Alt+V = Vendas  -   Alt+G = Contas Pagar   -    Alt+R = Contas a Receber   -  Orçamento =  ALt+O   -   Alt+D = PDV");
        jPanel2.add(jLabel6);

        jmArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Folder.png"))); // NOI18N
        jmArquivo.setText("Arquivo");

        jmiSobre.setText("Sobre o Sistema...");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSobre);
        jmArquivo.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jmArquivo.add(mnuSair);

        jMenuBar1.add(jmArquivo);

        jmCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Create.png"))); // NOI18N
        jmCadastrar.setText("Cadastros");

        jmiClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmiClientes.setText("Clientes");
        jmiClientes.setEnabled(false);
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiClientes);

        jmiProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jmiProdutos.setText("Produtos");
        jmiProdutos.setEnabled(false);
        jmiProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutosActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiProdutos);

        jmiFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jmiFornecedor.setText("Fornecedores");
        jmiFornecedor.setEnabled(false);
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiFornecedor);

        jmiUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jmiUsuario.setText("Usuário");
        jmiUsuario.setEnabled(false);
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiUsuario);

        miCidades.setText("Cidades");
        miCidades.setEnabled(false);
        miCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCidadesActionPerformed(evt);
            }
        });
        jmCadastrar.add(miCidades);

        miEmpresa.setText("Empresa");
        miEmpresa.setEnabled(false);
        miEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpresaActionPerformed(evt);
            }
        });
        jmCadastrar.add(miEmpresa);

        miUnidadeMedida.setText("Unidade de Medida");
        miUnidadeMedida.setEnabled(false);
        miUnidadeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnidadeMedidaActionPerformed(evt);
            }
        });
        jmCadastrar.add(miUnidadeMedida);

        miFormaPagamento.setText("Forma de Pagamento");
        miFormaPagamento.setEnabled(false);
        miFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFormaPagamentoActionPerformed(evt);
            }
        });
        jmCadastrar.add(miFormaPagamento);

        jMenuBar1.add(jmCadastrar);

        jmVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Shopping cart.png"))); // NOI18N
        jmVendas.setText("Vendas");

        jmiRegistrarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jmiRegistrarVenda.setText("Vendas");
        jmiRegistrarVenda.setEnabled(false);
        jmiRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarVendaActionPerformed(evt);
            }
        });
        jmVendas.add(jmiRegistrarVenda);

        jmiConsultarVenda.setText("Consultar vendas");
        jmiConsultarVenda.setEnabled(false);
        jmiConsultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarVendaActionPerformed(evt);
            }
        });
        jmVendas.add(jmiConsultarVenda);

        miOrcamento.setText("Orcamento");
        miOrcamento.setEnabled(false);
        miOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOrcamentoActionPerformed(evt);
            }
        });
        jmVendas.add(miOrcamento);

        miPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        miPDV.setText("Vendas em PDV");
        miPDV.setEnabled(false);
        miPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPDVActionPerformed(evt);
            }
        });
        jmVendas.add(miPDV);

        jmiDelivery.setText("Delivery");
        jmiDelivery.setEnabled(false);
        jmiDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDeliveryActionPerformed(evt);
            }
        });
        jmVendas.add(jmiDelivery);

        jMenuBar1.add(jmVendas);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Report.png"))); // NOI18N
        jMenu1.setText("Relatórios");

        jmiRelClientes.setText("Clientes");
        jmiRelClientes.setEnabled(false);
        jmiRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelClientes);

        jmiRelFornecedor.setText("Fornecedores");
        jmiRelFornecedor.setEnabled(false);
        jmiRelFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelFornecedor);

        jmiRelProdutos.setText("Produtos");
        jmiRelProdutos.setEnabled(false);
        jmiRelProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelProdutos);

        jmiRelatorioVendasPeriodo.setText("Vendas por peíodo");
        jmiRelatorioVendasPeriodo.setEnabled(false);
        jmiRelatorioVendasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioVendasPeriodoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioVendasPeriodo);

        jmiRelatorioVenda.setText("Venda unitária");
        jmiRelatorioVenda.setEnabled(false);
        jmiRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioVendaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioVenda);

        jmiRelatorioContasPagar.setText("Relatório de contas a pagar");
        jmiRelatorioContasPagar.setEnabled(false);
        jmiRelatorioContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioContasPagarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioContasPagar);

        miRelatorioContasReceber.setText("Relatório de contas a receber");
        miRelatorioContasReceber.setEnabled(false);
        miRelatorioContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioContasReceberActionPerformed(evt);
            }
        });
        jMenu1.add(miRelatorioContasReceber);

        jMenuItem1.setText("Gerador de código de barras");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jmAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Help.png"))); // NOI18N
        jmAjuda.setText("Ajuda");

        jMenuItem3.setText("Contato");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmAjuda.add(jMenuItem3);

        jMenuBar1.add(jmAjuda);

        jmFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Dollar.png"))); // NOI18N
        jmFinanceiro.setText("Financeiro");

        jmiContasPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jmiContasPagar.setText("Conta a pagar");
        jmiContasPagar.setEnabled(false);
        jmiContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContasPagarActionPerformed(evt);
            }
        });
        jmFinanceiro.add(jmiContasPagar);

        jmiContasReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jmiContasReceber.setText("Contas a receber");
        jmiContasReceber.setEnabled(false);
        jmiContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContasReceberActionPerformed(evt);
            }
        });
        jmFinanceiro.add(jmiContasReceber);

        miFluxoCaixa.setText("Fluxo de caixa");
        miFluxoCaixa.setEnabled(false);
        miFluxoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFluxoCaixaActionPerformed(evt);
            }
        });
        jmFinanceiro.add(miFluxoCaixa);

        jMenuBar1.add(jmFinanceiro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPainelDeFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPainelDeFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("BLBar Pro 1.0");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        JOptionPane.showMessageDialog(null, "BLVendas 2.0/ Atualização de 05/2015");
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        new ViewClientes().setVisible(true);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_jmiProdutosActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
        new ViewFornecedor().setVisible(true);
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void jmiRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_jmiRegistrarVendaActionPerformed

    private void jmiConsultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarVendaActionPerformed
        ViewVenda venda = new ViewVenda();
        venda.setViewConsultarVendas();
        venda.setVisible(true);
    }//GEN-LAST:event_jmiConsultarVendaActionPerformed

    private void jmiRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelClientesActionPerformed
        final AguardeGerandoRelatorio carregando = new AguardeGerandoRelatorio();
        final ControllerCliente controllerCliente = new ControllerCliente();
        carregando.setVisible(true);
        Thread t = new Thread() {
            @Override
            public void run() {
                // imprimir clientes
                controllerCliente.gerarRelatorioCliente();
                carregando.dispose();
            }
        };
        t.start();
    }//GEN-LAST:event_jmiRelClientesActionPerformed

    private void jmiRelFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelFornecedorActionPerformed
        final AguardeGerandoRelatorio carregando = new AguardeGerandoRelatorio();
        final ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
        carregando.setVisible(true);
        Thread t = new Thread() {
            @Override
            public void run() {
                // imrimir fornecedores
                controllerFornecedor.gerarRelatorioFornecedor();
                carregando.dispose();
            }
        };
        t.start();
    }//GEN-LAST:event_jmiRelFornecedorActionPerformed

    private void jmiRelProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelProdutosActionPerformed
        final AguardeGerandoRelatorio carregando = new AguardeGerandoRelatorio();
        final ControllerProdutos controllerProdutos = new ControllerProdutos();
        carregando.setVisible(true);
        Thread t = new Thread() {
            @Override
            public void run() {
                // imprimir produtos
                controllerProdutos.gerarRelatorioProdutos();
                carregando.dispose();
            }
        };
        t.start();
    }//GEN-LAST:event_jmiRelProdutosActionPerformed

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new ViewSobre(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmiRelatorioVendasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioVendasPeriodoActionPerformed
        // TODO add your handling code here:
        new ViewRelatorioVendas().setVisible(true);
    }//GEN-LAST:event_jmiRelatorioVendasPeriodoActionPerformed

    private void jmiRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioVendaActionPerformed
        // TODO add your handling code here:
        new ViewImprimirPDV(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jmiRelatorioVendaActionPerformed

    private void jmiContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContasPagarActionPerformed
        // TODO add your handling code here:
        new ViewContasPagar().setVisible(true);
    }//GEN-LAST:event_jmiContasPagarActionPerformed

    private void jmiContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContasReceberActionPerformed
        // TODO add your handling code here:
        new ViewContasReceber().setVisible(true);
    }//GEN-LAST:event_jmiContasReceberActionPerformed

    private void jmiRelatorioContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioContasPagarActionPerformed
        // TODO add your handling code here:
        new ViewRelatoriosContasPagar().setVisible(true);
    }//GEN-LAST:event_jmiRelatorioContasPagarActionPerformed

    private void miCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCidadesActionPerformed
        // TODO add your handling code here:
        new ViewCidade().setVisible(true);
    }//GEN-LAST:event_miCidadesActionPerformed

    private void miEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpresaActionPerformed
        // TODO add your handling code here:
        new ViewEmpresa().setVisible(true);
    }//GEN-LAST:event_miEmpresaActionPerformed

    private void miUnidadeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnidadeMedidaActionPerformed
        // TODO add your handling code here:
        new ViewUnidadeMedia().setVisible(true);
    }//GEN-LAST:event_miUnidadeMedidaActionPerformed

    private void miFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFormaPagamentoActionPerformed
        // TODO add your handling code here:
        new ViewFormaPagamento().setVisible(true);
    }//GEN-LAST:event_miFormaPagamentoActionPerformed

    private void miRelatorioContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioContasReceberActionPerformed
        // TODO add your handling code here:
        new ViewRelatoriosContasReceber().setVisible(true);
    }//GEN-LAST:event_miRelatorioContasReceberActionPerformed

    private void miOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOrcamentoActionPerformed
        // TODO add your handling code here:
        new ViewOrcamento().setVisible(true);
    }//GEN-LAST:event_miOrcamentoActionPerformed

    private void miPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPDVActionPerformed
        // TODO add your handling code here:
        new ViewPdv().setVisible(true);
    }//GEN-LAST:event_miPDVActionPerformed

    private void miFluxoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFluxoCaixaActionPerformed
        // TODO add your handling code here:
        new ViewFluxoCaixa().setVisible(true);
    }//GEN-LAST:event_miFluxoCaixaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ViewCodigobarras().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btFluxoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFluxoCaixaActionPerformed
        // TODO add your handling code here:
        new ViewFluxoCaixa().setVisible(true);
    }//GEN-LAST:event_btFluxoCaixaActionPerformed

    private void btContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContasReceberActionPerformed
        // acessar
        new ViewContasReceber().setVisible(true);
    }//GEN-LAST:event_btContasReceberActionPerformed

    private void btContaspagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaspagarActionPerformed
        // acessar
        new ViewContasPagar().setVisible(true);
    }//GEN-LAST:event_btContaspagarActionPerformed

    private void btPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPDVActionPerformed
        // TODO add your handling code here:
        new ViewPdv().setVisible(true);
    }//GEN-LAST:event_btPDVActionPerformed

    private void btVendaMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendaMesasActionPerformed
        // TODO add your handling code here:
        new ViewMesas().setVisible(true);
    }//GEN-LAST:event_btVendaMesasActionPerformed

    private void btRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_btRegistrarVendaActionPerformed

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btClienteActionPerformed

    private void btDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeliveryActionPerformed
        // TODO add your handling code here:
        new ViewDelivery().setVisible(true);
    }//GEN-LAST:event_btDeliveryActionPerformed

    private void jmiDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDeliveryActionPerformed
        // TODO add your handling code here:
        new ViewDelivery().setVisible(true);
    }//GEN-LAST:event_jmiDeliveryActionPerformed

    public String retornarUsuarioLogado(){
        return new ModelSessaoUsuario().nome;
    }
       
    private void cria() {
        JButton bt = new JButton("Código fonte");
        bt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new vreport().setVisible(true);
            }
        });
        
    }
    
    private void configurar(){
        pNomeUsuario = retornarUsuarioLogado();
        jlUsuario.setText(pNomeUsuario);
        BLDatas bLDatas = new BLDatas();
        jlData.setText(bLDatas.retornarDataHora());  
    }
    
    private void liberarModulos() {
        ControllerPermissaousuario controllerPermissaousuario = new ControllerPermissaousuario();
        ArrayList<ModelPermissaousuario> listaModelPermissaousuarios = new ArrayList<>();
        listaModelPermissaousuarios = controllerPermissaousuario.getListaPermissaousuarioController(new ModelSessaoUsuario().codigo);cria();
        for (int i = 0; i < listaModelPermissaousuarios.size(); i++) {
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("cliente")) {
                jmiRelClientes.setEnabled(true);
                jmiClientes.setEnabled(true);
                btCliente.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("produto")) {
                btProdutos.setEnabled(true);
                jmiRelProdutos.setEnabled(true);
                jmiProdutos.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("fornecedor")) {
                jmiFornecedor.setEnabled(true);
                jmiRelFornecedor.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("usuario")) {
                jmiUsuario.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("venda")) {
                btRegistrarVenda.setEnabled(true);
                jmiRegistrarVenda.setEnabled(true);
                jmiConsultarVenda.setEnabled(true);
                jmiRelatorioVenda.setEnabled(true);
                jmiRelatorioVendasPeriodo.setEnabled(true);
                btPDV.setEnabled(true);
                miPDV.setEnabled(true);
                btDelivery.setEnabled(true);
                jmiDelivery.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("pagar")) {
                btContaspagar.setEnabled(true);
                jmiContasPagar.setEnabled(true);
                jmiRelatorioContasPagar.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("receber")) {
                btContasReceber.setEnabled(true);
                jmiContasReceber.setEnabled(true);
                miRelatorioContasReceber.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("caixa")) {           
                jmiRelatorioContasPagar.setEnabled(true);
                miFluxoCaixa.setEnabled(true);
                btFluxoCaixa.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("empresa")) {           
                miEmpresa.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("fornecedor")) {           
                jmiFornecedor.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("cidade")) {           
                miCidades.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("unidade")) {           
                miUnidadeMedida.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("pagamento")) {           
                miFormaPagamento.setEnabled(true);
            }
            if (listaModelPermissaousuarios.get(i).getPermissao().equals("orcamento")) {           
                miOrcamento.setEnabled(true);
                btVendaMesas.setEnabled(true);
            }
        }
    }
    
    public void centralizarContainer(Component pai, Component filho) {

        // obter dimensões do pai  
        int larguraPai = pai.getWidth();
        int alturaPai = pai.getHeight();
        // obter dimensões do filho  
        int larguraFilho = filho.getWidth();
        int alturaFilho = filho.getWidth();
        // calcular novas coordenadas do filho  
        int novoX = (larguraPai - larguraFilho) / 2;
        int novoY = (alturaPai - alturaFilho) / 2;
        // centralizar filho  
        filho.setLocation(novoX, novoY);
        pai.repaint();
        filho.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewiPrincipal().setVisible(true);             
            }
        });
    }
    
 
 
    // Estados da calculadora
    public enum estadosDaCalculadora {
        INICIANDO,
        PRIMEIRA_DIGITACAO,
        EM_OPERACAO,
        NOVA_DIGITACAO,
        TOTALIZANDO
    }
 
 
 
    // Operações da calculadora
    public enum operacoesCalculadora {
        SOMA,
        SUBTRAI,
        MULTIPLICA,
        DIVIDI
    }
 
 
   // Propriedades para controle interno
    private estadosDaCalculadora estado = estadosDaCalculadora.INICIANDO;
    private operacoesCalculadora operacao;
    private double acumulador;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btContasReceber;
    private javax.swing.JButton btContaspagar;
    private javax.swing.JButton btDelivery;
    private javax.swing.JButton btFluxoCaixa;
    private javax.swing.JButton btPDV;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btRegistrarVenda;
    private javax.swing.JButton btVendaMesas;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmFinanceiro;
    private javax.swing.JMenu jmVendas;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiConsultarVenda;
    private javax.swing.JMenuItem jmiContasPagar;
    private javax.swing.JMenuItem jmiContasReceber;
    private javax.swing.JMenuItem jmiDelivery;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiProdutos;
    private javax.swing.JMenuItem jmiRegistrarVenda;
    private javax.swing.JMenuItem jmiRelClientes;
    private javax.swing.JMenuItem jmiRelFornecedor;
    private javax.swing.JMenuItem jmiRelProdutos;
    private javax.swing.JMenuItem jmiRelatorioContasPagar;
    private javax.swing.JMenuItem jmiRelatorioVenda;
    private javax.swing.JMenuItem jmiRelatorioVendasPeriodo;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem jmiUsuario;
    private javax.swing.JPanel jpMenuCentral;
    private componentes.UJPanelImagem jpPainelDeFundo;
    private javax.swing.JMenuItem miCidades;
    private javax.swing.JMenuItem miEmpresa;
    private javax.swing.JMenuItem miFluxoCaixa;
    private javax.swing.JMenuItem miFormaPagamento;
    private javax.swing.JMenuItem miOrcamento;
    private javax.swing.JMenuItem miPDV;
    private javax.swing.JMenuItem miRelatorioContasReceber;
    private javax.swing.JMenuItem miUnidadeMedida;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables

    private void JButton() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
